In [6]:
import numpy as np

In [8]:
c = np.zeros(8)
c

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
c.shape

(8,)

In [10]:
d = np.zeros((4, 3))
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
d.shape

(4, 3)

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<function shape at 0x10ae27ab0>

In [13]:
A = np.array([[1, 5], [4, -2]])
A

array([[ 1,  5],
       [ 4, -2]])

In [8]:
B = np.array([[2, -1], [7, 6]])
B

array([[ 2, -1],
       [ 7,  6]])

In [9]:
A + B

array([[ 3,  4],
       [11,  4]])

In [10]:
A - B

array([[-1,  6],
       [-3, -8]])

In [11]:
np.dot(A, B)

array([[ 37,  29],
       [ -6, -16]])

In [12]:
A = np.array([[1, 5, -2], [4, 0, -3], [-8, 2, 6]])
A

array([[ 1,  5, -2],
       [ 4,  0, -3],
       [-8,  2,  6]])

In [13]:
A.sum()

5

In [14]:
A.max()

6

In [15]:
A.min()

-8

In [16]:
np.average(A)

0.5555555555555556

In [17]:
np.median(A)

1.0

In [18]:
np.var(A)

17.358024691358025

In [19]:
np.std(A)

4.166296279833928

In [20]:
A = np.array([[1, 5], [4, -2]])
A

array([[ 1,  5],
       [ 4, -2]])

In [21]:
a = np.linalg.det(A)
a

-22.000000000000004

In [22]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.09090909,  0.22727273],
       [ 0.18181818, -0.04545455]])

In [23]:
np.dot(A, A_inv)

array([[ 1.00000000e+00, -1.38777878e-17],
       [ 0.00000000e+00,  1.00000000e+00]])

In [58]:
import pandas as pd

In [12]:
df = pd.read_csv("weather.csv")

In [13]:
df

年月日  平均気温(℃) 平均気温(℃).1 平均気温(℃).2  最高気温(℃) 最高気温(℃).1 最高気温(℃).2  \
0           NaN      NaN      品質情報      均質番号      NaN      品質情報      均質番号   
1    2019/12/14      9.3         8         1     15.9         8         1   
2    2019/12/15      7.8         8         1     11.1         8         1   
3    2019/12/16      6.9         8         1     12.5         8         1   
4    2019/12/17      8.2         8         1     10.3         8         1   
..          ...      ...       ...       ...      ...       ...       ...   
363  2020/12/10      8.7         8         1     11.1         8         1   
364  2020/12/11      9.2         8         1     13.8         8         1   
365  2020/12/12     10.4         8         1     14.0         8         1   
366  2020/12/13      8.6         8         1     14.4         8         1   
367  2020/12/14      7.8         8         1     12.2         8         1   

     最低気温(℃) 最低気温(℃).1 最低気温(℃).2  ...  平均雲量(10分比).2 平均蒸気圧(hPa) 平均蒸気圧(hPa).1  \
0        NaN      品質情報      均質番号  ...          均質番号        NaN         品質情報   
1        3.2         8         1  ...             1        NaN            0   
2        4.0         8         1  ...             1        NaN            0   
3        1.3         8         1  ...             1        NaN            0   
4        5.7         8         1  ...             1        NaN            0   
..       ...       ...       ...  ...           ...        ...          ...   
363      6.0         8         1  ...             1        NaN            0   
364      3.5         8         1  ...             1        NaN            0   
365      8.0         8         1  ...             1        NaN            0   
366      4.4         8         1  ...             1        NaN            0   
367      4.4         8         1  ...             1        NaN            0   

     平均蒸気圧(hPa).2 平均風速(m/s) 平均風速(m/s).1  平均風速(m/s).2 日照時間(時間) 日照時間(時間).1  \
0            均質番号       NaN        品質情報         均質番号      NaN       品質情報   
1               1       2.0           8            1      8.9          8   
2               1       2.3           8            1      6.3          8   
3               1       1.1           8            1      8.9          8   
4               1       1.1           8            1      0.2          8   
..            ...       ...         ...          ...      ...        ...   
363             1       1.4           8            1      0.0          8   
364             1       0.8           8            1      4.3          8   
365             1       1.4           8            1      1.4          8   
366             1       1.0           8            1      5.5          8   
367             1       1.9           8            1      4.4          8   

     日照時間(時間).2  
0          均質番号  
1             1  
2             1  
3             1  
4             1  
..          ...  
363           1  
364           1  
365           1  
366           1  
367           1  

[368 rows x 28 columns]

In [28]:
df.head(3)

年月日  平均気温(℃) 平均気温(℃).1 平均気温(℃).2  最高気温(℃) 最高気温(℃).1 最高気温(℃).2  \
0         NaN      NaN      品質情報      均質番号      NaN      品質情報      均質番号   
1  2019/12/14      9.3         8         1     15.9         8         1   
2  2019/12/15      7.8         8         1     11.1         8         1   

   最低気温(℃) 最低気温(℃).1 最低気温(℃).2  ...  平均雲量(10分比).2 平均蒸気圧(hPa) 平均蒸気圧(hPa).1  \
0      NaN      品質情報      均質番号  ...          均質番号        NaN         品質情報   
1      3.2         8         1  ...             1        NaN            0   
2      4.0         8         1  ...             1        NaN            0   

   平均蒸気圧(hPa).2 平均風速(m/s) 平均風速(m/s).1  平均風速(m/s).2 日照時間(時間) 日照時間(時間).1  \
0          均質番号       NaN        品質情報         均質番号      NaN       品質情報   
1             1       2.0           8            1      8.9          8   
2             1       2.3           8            1      6.3          8   

   日照時間(時間).2  
0        均質番号  
1           1  
2           1  

[3 rows x 28 columns]

In [30]:
df.tail(10)

年月日  平均気温(℃) 平均気温(℃).1 平均気温(℃).2  最高気温(℃) 最高気温(℃).1 最高気温(℃).2  \
358   2020/12/5      6.0         8         1      7.3         8         1   
359   2020/12/6      8.0         8         1     13.3         8         1   
360   2020/12/7      9.0         8         1     16.0         8         1   
361   2020/12/8     10.4         8         1     16.0         8         1   
362   2020/12/9      9.2         8         1     11.2         8         1   
363  2020/12/10      8.7         8         1     11.1         8         1   
364  2020/12/11      9.2         8         1     13.8         8         1   
365  2020/12/12     10.4         8         1     14.0         8         1   
366  2020/12/13      8.6         8         1     14.4         8         1   
367  2020/12/14      7.8         8         1     12.2         8         1   

     最低気温(℃) 最低気温(℃).1 最低気温(℃).2  ...  平均雲量(10分比).2 平均蒸気圧(hPa) 平均蒸気圧(hPa).1  \
358      4.3         8         1  ...             1        NaN            0   
359      4.5         8         1  ...             1        NaN            0   
360      4.2         8         1  ...             1        NaN            0   
361      4.6         8         1  ...             1        NaN            0   
362      8.3         8         1  ...             1        NaN            0   
363      6.0         8         1  ...             1        NaN            0   
364      3.5         8         1  ...             1        NaN            0   
365      8.0         8         1  ...             1        NaN            0   
366      4.4         8         1  ...             1        NaN            0   
367      4.4         8         1  ...             1        NaN            0   

     平均蒸気圧(hPa).2 平均風速(m/s) 平均風速(m/s).1  平均風速(m/s).2 日照時間(時間) 日照時間(時間).1  \
358             1       1.4           8            1      0.0          8   
359             1       1.0           8            1      3.8          8   
360             1       0.7           8            1      9.0          8   
361             1       1.3           8            1      6.9          8   
362             1       1.4           8            1      0.0          8   
363             1       1.4           8            1      0.0          8   
364             1       0.8           8            1      4.3          8   
365             1       1.4           8            1      1.4          8   
366             1       1.0           8            1      5.5          8   
367             1       1.9           8            1      4.4          8   

     日照時間(時間).2  
358           1  
359           1  
360           1  
361           1  
362           1  
363           1  
364           1  
365           1  
366           1  
367           1  

[10 rows x 28 columns]

In [31]:
df.head()

年月日  平均気温(℃) 平均気温(℃).1 平均気温(℃).2  最高気温(℃) 最高気温(℃).1 最高気温(℃).2  \
0         NaN      NaN      品質情報      均質番号      NaN      品質情報      均質番号   
1  2019/12/14      9.3         8         1     15.9         8         1   
2  2019/12/15      7.8         8         1     11.1         8         1   
3  2019/12/16      6.9         8         1     12.5         8         1   
4  2019/12/17      8.2         8         1     10.3         8         1   

   最低気温(℃) 最低気温(℃).1 最低気温(℃).2  ...  平均雲量(10分比).2 平均蒸気圧(hPa) 平均蒸気圧(hPa).1  \
0      NaN      品質情報      均質番号  ...          均質番号        NaN         品質情報   
1      3.2         8         1  ...             1        NaN            0   
2      4.0         8         1  ...             1        NaN            0   
3      1.3         8         1  ...             1        NaN            0   
4      5.7         8         1  ...             1        NaN            0   

   平均蒸気圧(hPa).2 平均風速(m/s) 平均風速(m/s).1  平均風速(m/s).2 日照時間(時間) 日照時間(時間).1  \
0          均質番号       NaN        品質情報         均質番号      NaN       品質情報   
1             1       2.0           8            1      8.9          8   
2             1       2.3           8            1      6.3          8   
3             1       1.1           8            1      8.9          8   
4             1       1.1           8            1      0.2          8   

   日照時間(時間).2  
0        均質番号  
1           1  
2           1  
3           1  
4           1  

[5 rows x 28 columns]

In [32]:
df.columns

Index(['年月日', '平均気温(℃)', '平均気温(℃).1', '平均気温(℃).2', '最高気温(℃)', '最高気温(℃).1',
       '最高気温(℃).2', '最低気温(℃)', '最低気温(℃).1', '最低気温(℃).2', '降水量の合計(mm)',
       '降水量の合計(mm).1', '降水量の合計(mm).2', '最深積雪(cm)', '最深積雪(cm).1', '最深積雪(cm).2',
       '平均雲量(10分比)', '平均雲量(10分比).1', '平均雲量(10分比).2', '平均蒸気圧(hPa)',
       '平均蒸気圧(hPa).1', '平均蒸気圧(hPa).2', '平均風速(m/s)', '平均風速(m/s).1',
       '平均風速(m/s).2', '日照時間(時間)', '日照時間(時間).1', '日照時間(時間).2'],
      dtype='object')

In [14]:
df [['年月日', 
     '平均気温(℃)',
     '最高気温(℃)',  
     '最低気温(℃)', 
     '降水量の合計(mm)',
     '最深積雪(cm)', 
     '平均雲量(10分比)', 
     '平均蒸気圧(hPa)',
     '平均風速(m/s)', 
     '日照時間(時間)',
    ]]

年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)  平均雲量(10分比)  \
0           NaN      NaN      NaN      NaN         NaN       NaN         NaN   
1    2019/12/14      9.3     15.9      3.2         0.0       NaN         NaN   
2    2019/12/15      7.8     11.1      4.0         0.0       NaN         NaN   
3    2019/12/16      6.9     12.5      1.3         0.0       NaN         NaN   
4    2019/12/17      8.2     10.3      5.7         2.0       NaN         NaN   
..          ...      ...      ...      ...         ...       ...         ...   
363  2020/12/10      8.7     11.1      6.0         0.5       NaN         NaN   
364  2020/12/11      9.2     13.8      3.5         0.0       NaN         NaN   
365  2020/12/12     10.4     14.0      8.0         0.0       NaN         NaN   
366  2020/12/13      8.6     14.4      4.4         0.0       NaN         NaN   
367  2020/12/14      7.8     12.2      4.4         0.0       NaN         NaN   

     平均蒸気圧(hPa)  平均風速(m/s)  日照時間(時間)  
0           NaN        NaN       NaN  
1           NaN        2.0       8.9  
2           NaN        2.3       6.3  
3           NaN        1.1       8.9  
4           NaN        1.1       0.2  
..          ...        ...       ...  
363         NaN        1.4       0.0  
364         NaN        0.8       4.3  
365         NaN        1.4       1.4  
366         NaN        1.0       5.5  
367         NaN        1.9       4.4  

[368 rows x 10 columns]

In [15]:
df = df[['年月日', 
     '平均気温(℃)',
     '最高気温(℃)',  
     '最低気温(℃)', 
     '降水量の合計(mm)',
     '最深積雪(cm)', 
     '平均雲量(10分比)', 
     '平均蒸気圧(hPa)',
     '平均風速(m/s)', 
     '日照時間(時間)',
    ]][1:]

In [53]:
df.head()

年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)  平均雲量(10分比)  \
1  2019/12/14      9.3     15.9      3.2         0.0       NaN         NaN   
2  2019/12/15      7.8     11.1      4.0         0.0       NaN         NaN   
3  2019/12/16      6.9     12.5      1.3         0.0       NaN         NaN   
4  2019/12/17      8.2     10.3      5.7         2.0       NaN         NaN   
5  2019/12/18      9.9     15.0      4.8         0.0       NaN         NaN   

   平均蒸気圧(hPa)  平均風速(m/s)  日照時間(時間)  
1         NaN        2.0       8.9  
2         NaN        2.3       6.3  
3         NaN        1.1       8.9  
4         NaN        1.1       0.2  
5         NaN        1.2       4.3

In [63]:
df.max()

年月日           2020/9/9
平均気温(℃)           31.2
最高気温(℃)           37.2
最低気温(℃)           27.8
降水量の合計(mm)        77.5
最深積雪(cm)           NaN
平均雲量(10分比)         NaN
平均蒸気圧(hPa)         NaN
平均風速(m/s)          4.4
日照時間(時間)          13.5
dtype: object

In [54]:
df.min()

年月日           2019/12/14
平均気温(℃)              1.8
最高気温(℃)              5.5
最低気温(℃)             -4.3
降水量の合計(mm)           0.0
最深積雪(cm)             NaN
平均雲量(10分比)           NaN
平均蒸気圧(hPa)           NaN
平均風速(m/s)            0.7
日照時間(時間)             0.0
dtype: object

In [38]:
df.dtypes

年月日            object
平均気温(℃)       float64
最高気温(℃)       float64
最低気温(℃)       float64
降水量の合計(mm)    float64
最深積雪(cm)      float64
平均雲量(10分比)    float64
平均蒸気圧(hPa)    float64
平均風速(m/s)     float64
日照時間(時間)      float64
dtype: object

In [39]:
df.shape

(366, 10)

In [40]:
df.columns

Index(['年月日', '平均気温(℃)', '最高気温(℃)', '最低気温(℃)', '降水量の合計(mm)', '最深積雪(cm)',
       '平均雲量(10分比)', '平均蒸気圧(hPa)', '平均風速(m/s)', '日照時間(時間)'],
      dtype='object')

In [43]:
df.index

RangeIndex(start=2, stop=368, step=1)

In [16]:
df.iloc[4:10, 2:6]

最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)
5      15.0      4.8         0.0       NaN
6       9.7      7.9         1.0       NaN
7      15.8      5.7         0.0       NaN
8       8.4      6.5         0.0       NaN
9       9.8      4.2        21.0       NaN
10     12.1      3.6         9.5       NaN

In [37]:
df_people = pd.read_csv("people.csv")
df_people

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
2   35  31    Suzuki       Japan
3   16  20      John     America
4   28  11       Kim       Korea

In [48]:
df_people['nationality']

0      Japan
1    America
2      Japan
3    America
4      Korea
Name: nationality, dtype: object

In [49]:
df_people['nationality'] == 'America'

0    False
1     True
2    False
3     True
4    False
Name: nationality, dtype: bool

In [50]:
df_people[df_people['nationality'] == 'America']

age  id  name nationality
1   21  33  Mike     America
3   16  20  John     America

In [52]:
df_people.query('nationality == "America"')

age  id  name nationality
1   21  33  Mike     America
3   16  20  John     America

In [53]:
df_people['age'] >= 20

0     True
1     True
2     True
3    False
4     True
Name: age, dtype: bool

In [54]:
df_people['age'] < 30

0     True
1     True
2    False
3     True
4     True
Name: age, dtype: bool

In [56]:
(df_people['age'] >= 20)& (df_people['age'] < 30)

0     True
1     True
2    False
3    False
4     True
Name: age, dtype: bool

In [57]:
df_people[(df_people['age'] >= 20)& (df_people['age'] < 30)]

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
4   28  11       Kim       Korea

In [41]:
df_people['nationality'].unique()

array(['Japan', 'America', 'Korea'], dtype=object)

In [43]:
pd.get_dummies(df_people, columns=['nationality'])

age  id      name  nationality_America  nationality_Japan  \
0   26  13  Imanishi                False               True   
1   21  33      Mike                 True              False   
2   35  31    Suzuki                False               True   
3   16  20      John                 True              False   
4   28  11       Kim                False              False   

   nationality_Korea  
0              False  
1              False  
2              False  
3              False  
4               True

In [60]:
df_people

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
2   35  31    Suzuki       Japan
3   16  20      John     America
4   28  11       Kim       Korea

In [62]:
df_people.drop_duplicates(subset='nationality')

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
4   28  11       Kim       Korea

In [66]:
df_people.rename(columns={
    'name':' firstname',
}).head()

age  id  firstname nationality
0   26  13   Imanishi       Japan
1   21  33       Mike     America
2   35  31     Suzuki       Japan
3   16  20       John     America
4   28  11        Kim       Korea

In [67]:
df_people.rename(columns={
    'firstname':'name',
}).head()

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
2   35  31    Suzuki       Japan
3   16  20      John     America
4   28  11       Kim       Korea

In [18]:
import pandas as pd

In [19]:
df = pd.read_csv("weather.csv")

In [20]:
df

年月日  平均気温(℃) 平均気温(℃).1 平均気温(℃).2  最高気温(℃) 最高気温(℃).1 最高気温(℃).2  \
0           NaN      NaN      品質情報      均質番号      NaN      品質情報      均質番号   
1    2019/12/14      9.3         8         1     15.9         8         1   
2    2019/12/15      7.8         8         1     11.1         8         1   
3    2019/12/16      6.9         8         1     12.5         8         1   
4    2019/12/17      8.2         8         1     10.3         8         1   
..          ...      ...       ...       ...      ...       ...       ...   
363  2020/12/10      8.7         8         1     11.1         8         1   
364  2020/12/11      9.2         8         1     13.8         8         1   
365  2020/12/12     10.4         8         1     14.0         8         1   
366  2020/12/13      8.6         8         1     14.4         8         1   
367  2020/12/14      7.8         8         1     12.2         8         1   

     最低気温(℃) 最低気温(℃).1 最低気温(℃).2  ...  平均雲量(10分比).2 平均蒸気圧(hPa) 平均蒸気圧(hPa).1  \
0        NaN      品質情報      均質番号  ...          均質番号        NaN         品質情報   
1        3.2         8         1  ...             1        NaN            0   
2        4.0         8         1  ...             1        NaN            0   
3        1.3         8         1  ...             1        NaN            0   
4        5.7         8         1  ...             1        NaN            0   
..       ...       ...       ...  ...           ...        ...          ...   
363      6.0         8         1  ...             1        NaN            0   
364      3.5         8         1  ...             1        NaN            0   
365      8.0         8         1  ...             1        NaN            0   
366      4.4         8         1  ...             1        NaN            0   
367      4.4         8         1  ...             1        NaN            0   

     平均蒸気圧(hPa).2 平均風速(m/s) 平均風速(m/s).1  平均風速(m/s).2 日照時間(時間) 日照時間(時間).1  \
0            均質番号       NaN        品質情報         均質番号      NaN       品質情報   
1               1       2.0           8            1      8.9          8   
2               1       2.3           8            1      6.3          8   
3               1       1.1           8            1      8.9          8   
4               1       1.1           8            1      0.2          8   
..            ...       ...         ...          ...      ...        ...   
363             1       1.4           8            1      0.0          8   
364             1       0.8           8            1      4.3          8   
365             1       1.4           8            1      1.4          8   
366             1       1.0           8            1      5.5          8   
367             1       1.9           8            1      4.4          8   

     日照時間(時間).2  
0          均質番号  
1             1  
2             1  
3             1  
4             1  
..          ...  
363           1  
364           1  
365           1  
366           1  
367           1  

[368 rows x 28 columns]

In [21]:
df.sort_values('最高気温(℃)', ascending=True)

年月日  平均気温(℃) 平均気温(℃).1 平均気温(℃).2  最高気温(℃) 最高気温(℃).1 最高気温(℃).2  \
55    2020/2/6      2.3         8         1      5.5         8         1   
36   2020/1/18      3.8         8         1      6.2         8         1   
40   2020/1/22      4.0         8         1      6.2         8         1   
45   2020/1/27      4.7         8         1      6.8         8         1   
56    2020/2/7      1.8         8         1      7.0         8         1   
..         ...      ...       ...       ...      ...       ...       ...   
243  2020/8/12     30.3         8         1     35.9         8         1   
246  2020/8/15     31.2         8         1     36.5         8         1   
244  2020/8/13     30.4         8         1     37.1         8         1   
248  2020/8/17     30.9         8         1     37.2         8         1   
0          NaN      NaN      品質情報      均質番号      NaN      品質情報      均質番号   

     最低気温(℃) 最低気温(℃).1 最低気温(℃).2  ...  平均雲量(10分比).2 平均蒸気圧(hPa) 平均蒸気圧(hPa).1  \
55      -1.3         8         1  ...             1        NaN            0   
36       0.9         8         1  ...             1        NaN            0   
40       1.4         8         1  ...             1        NaN            0   
45       3.1         8         1  ...             1        NaN            0   
56      -4.3         8         1  ...             1        NaN            0   
..       ...       ...       ...  ...           ...        ...          ...   
243     27.6         8         1  ...             1        NaN            0   
246     27.8         8         1  ...             1        NaN            0   
244     26.9         8         1  ...             1        NaN            0   
248     26.8         8         1  ...             1        NaN            0   
0        NaN      品質情報      均質番号  ...          均質番号        NaN         品質情報   

     平均蒸気圧(hPa).2 平均風速(m/s) 平均風速(m/s).1  平均風速(m/s).2 日照時間(時間) 日照時間(時間).1  \
55              1       3.6           8            1      7.5          8   
36              1       2.5           8            1      0.0          8   
40              1       1.2           8            1      0.9          8   
45              1       1.6           8            1      0.0          8   
56              1       1.1           8            1      6.7          8   
..            ...       ...         ...          ...      ...        ...   
243             1       1.8           8            1      7.2          8   
246             1       1.5           8            1      8.7          8   
244             1       1.6           8            1      8.5          8   
248             1       1.7           8            1      9.4          8   
0            均質番号       NaN        品質情報         均質番号      NaN       品質情報   

     日照時間(時間).2  
55            1  
36            1  
40            1  
45            1  
56            1  
..          ...  
243           1  
246           1  
244           1  
248           1  
0          均質番号  

[368 rows x 28 columns]

In [25]:
df [['年月日', 
     '平均気温(℃)',
     '最高気温(℃)',  
     '最低気温(℃)', 
     '降水量の合計(mm)',
     '最深積雪(cm)', 
     '平均雲量(10分比)', 
     '平均蒸気圧(hPa)',
     '平均風速(m/s)', 
     '日照時間(時間)',
    ]]

年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)  平均雲量(10分比)  \
0           NaN      NaN      NaN      NaN         NaN       NaN         NaN   
1    2019/12/14      9.3     15.9      3.2         0.0       NaN         NaN   
2    2019/12/15      7.8     11.1      4.0         0.0       NaN         NaN   
3    2019/12/16      6.9     12.5      1.3         0.0       NaN         NaN   
4    2019/12/17      8.2     10.3      5.7         2.0       NaN         NaN   
..          ...      ...      ...      ...         ...       ...         ...   
363  2020/12/10      8.7     11.1      6.0         0.5       NaN         NaN   
364  2020/12/11      9.2     13.8      3.5         0.0       NaN         NaN   
365  2020/12/12     10.4     14.0      8.0         0.0       NaN         NaN   
366  2020/12/13      8.6     14.4      4.4         0.0       NaN         NaN   
367  2020/12/14      7.8     12.2      4.4         0.0       NaN         NaN   

     平均蒸気圧(hPa)  平均風速(m/s)  日照時間(時間)  
0           NaN        NaN       NaN  
1           NaN        2.0       8.9  
2           NaN        2.3       6.3  
3           NaN        1.1       8.9  
4           NaN        1.1       0.2  
..          ...        ...       ...  
363         NaN        1.4       0.0  
364         NaN        0.8       4.3  
365         NaN        1.4       1.4  
366         NaN        1.0       5.5  
367         NaN        1.9       4.4  

[368 rows x 10 columns]

In [26]:
df.rename(columns={
    '平均気温(℃)':'平均気温',
    '最高気温(℃)':'最高気温',	
    '最低気温(℃)':'最低気温',	
    '降水量の合計(mm)' : '降水量の合計',
    '最深積雪(cm)':'最深積雪',
    '平均雲量(10分比)':'平均雲量',
    '平均蒸気圧(hPa)':'平均蒸気圧',
    '平均風速(m/s)':'平均風速',
    '日照時間(時間)':'日照時間',
}).head()

年月日  平均気温 平均気温(℃).1 平均気温(℃).2  最高気温 最高気温(℃).1 最高気温(℃).2  最低気温  \
0         NaN   NaN      品質情報      均質番号   NaN      品質情報      均質番号   NaN   
1  2019/12/14   9.3         8         1  15.9         8         1   3.2   
2  2019/12/15   7.8         8         1  11.1         8         1   4.0   
3  2019/12/16   6.9         8         1  12.5         8         1   1.3   
4  2019/12/17   8.2         8         1  10.3         8         1   5.7   

  最低気温(℃).1 最低気温(℃).2  ...  平均雲量(10分比).2 平均蒸気圧 平均蒸気圧(hPa).1  平均蒸気圧(hPa).2  \
0      品質情報      均質番号  ...          均質番号   NaN         品質情報          均質番号   
1         8         1  ...             1   NaN            0             1   
2         8         1  ...             1   NaN            0             1   
3         8         1  ...             1   NaN            0             1   
4         8         1  ...             1   NaN            0             1   

  平均風速 平均風速(m/s).1  平均風速(m/s).2 日照時間 日照時間(時間).1  日照時間(時間).2  
0  NaN        品質情報         均質番号  NaN       品質情報        均質番号  
1  2.0           8            1  8.9          8           1  
2  2.3           8            1  6.3          8           1  
3  1.1           8            1  8.9          8           1  
4  1.1           8            1  0.2          8           1  

[5 rows x 28 columns]

In [3]:
import matplotlib.pyplot as plt

In [35]:
df.sort_values('最高気温', ascending=True)

KeyError: '最高気温'

In [95]:
df_people['nationality'].unique()

array(['Japan', 'America', 'Korea'], dtype=object)

In [101]:
pd.get_dummies(df_people, columns=['nationality'])

age  id      name  nationality_America  nationality_Japan  \
0   26  13  Imanishi                False               True   
1   21  33      Mike                 True              False   
2   35  31    Suzuki                False               True   
3   16  20      John                 True              False   
4   28  11       Kim                False              False   

   nationality_Korea  
0              False  
1              False  
2              False  
3              False  
4               True

In [8]:
import pandas as pd

In [9]:
df_iris = pd.read_csv('iris.csv')

In [45]:
df_iris

sepal-length  sepal-width  petal-length  petal-width            Class
0             5.1          3.5           1.4          0.2      Iris-setosa
1             4.9          3.0           1.4          0.2      Iris-setosa
2             4.7          3.2           1.3          0.2      Iris-setosa
3             4.6          3.1           1.5          0.2      Iris-setosa
4             5.0          3.6           1.4          0.2      Iris-setosa
..            ...          ...           ...          ...              ...
151          12.5          3.1           5.1          1.8   Iris-virginica
152          13.4          2.7           5.1          1.8   Iris-virginica
153          13.2          3.2           5.1          1.8  Iris-versicolor
154          15.2          2.3           5.1          1.8  Iris-versicolor
155          14.2          2.4           5.1          1.8  Iris-versicolor

[156 rows x 5 columns]

In [10]:
df_iris.groupby('Class').mean()

sepal-length  sepal-width  petal-length  petal-width
Class                                                                
Iris-setosa          5.004255     3.434000      1.454000     0.244000
Iris-versicolor      6.403774     2.762264      4.307547     1.352830
Iris-virginica       6.937736     2.979245      5.526415     2.013208

NameError: name 'df' is not defined

In [46]:
df_iris.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [47]:
df_iris.groupby('Class').mean()

sepal-length  sepal-width  petal-length  petal-width
Class                                                                
Iris-setosa          5.004255     3.434000      1.454000     0.244000
Iris-versicolor      6.403774     2.762264      4.307547     1.352830
Iris-virginica       6.937736     2.979245      5.526415     2.013208

In [113]:
df

年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)  平均雲量(10分比)  \
2    2019/12/15      7.8     11.1      4.0         0.0       NaN         NaN   
3    2019/12/16      6.9     12.5      1.3         0.0       NaN         NaN   
4    2019/12/17      8.2     10.3      5.7         2.0       NaN         NaN   
5    2019/12/18      9.9     15.0      4.8         0.0       NaN         NaN   
6    2019/12/19      8.6      9.7      7.9         1.0       NaN         NaN   
..          ...      ...      ...      ...         ...       ...         ...   
363  2020/12/10      8.7     11.1      6.0         0.5       NaN         NaN   
364  2020/12/11      9.2     13.8      3.5         0.0       NaN         NaN   
365  2020/12/12     10.4     14.0      8.0         0.0       NaN         NaN   
366  2020/12/13      8.6     14.4      4.4         0.0       NaN         NaN   
367  2020/12/14      7.8     12.2      4.4         0.0       NaN         NaN   

     平均蒸気圧(hPa)  平均風速(m/s)  日照時間(時間)  
2           NaN        2.3       6.3  
3           NaN        1.1       8.9  
4           NaN        1.1       0.2  
5           NaN        1.2       4.3  
6           NaN        1.3       0.0  
..          ...        ...       ...  
363         NaN        1.4       0.0  
364         NaN        0.8       4.3  
365         NaN        1.4       1.4  
366         NaN        1.0       5.5  
367         NaN        1.9       4.4  

[366 rows x 10 columns]