In [1]:
class Person:
    __nationality = 'Japan'

    def __init__(self, name):
        self.name = name
        
    def say_hello(self):
        print(f'Hello! My nationality is {self.__nationality}')

    def __say_my_name(self):
        print(f'My name is {self.name}')

In [2]:
sable = Person('SABLE')

In [3]:
sable.name

'SABLE'

In [4]:
sable.__nationality

AttributeError: 'Person' object has no attribute '__nationality'

In [2]:
sable__say_my_name

NameError: name 'sable__say_my_name' is not defined

In [6]:
file = open('sample.txt')
text = file.read()
file.close()

In [7]:
print(text)

Hi my name is Sachiyo.
How are you doing ?


In [15]:
with open ('sample.txt', 'r') as f:
    text = f.read()

In [16]:
print(text)

Hi my name is Sachiyo.
How are you doing ?


In [11]:
file = open('sample.txt')
text = file.read()
file.close()

In [12]:
print(text)

Bonjour, Je m'appelle Sachiyo
Bonne année !!!


In [13]:
with open('sample.txt', 'r') as f:
    text = f.read()

In [14]:
print(text)

Bonjour, Je m'appelle Sachiyo
Bonne année !!!


In [21]:
import json

In [27]:
with open('sample.json', 'r') as f:
    data = json.load(f)

In [28]:
data

{'store_name': '神田店',
 'items': [{'item_id': 0, 'item_name': 'コーラ'},
  {'item_id': 1, 'item_name': '唐揚げ弁当'},
  {'item_id': 2, 'item_name': '週刊誌'}]}

In [29]:
data['store_name']

'神田店'

In [9]:
import os

In [10]:
for curDir, dirs, files in os.walk('.'):
    print(files)

['people.csv', 'question81_100.ipynb', 'test_docPython.ipynb', 'Matplotlib.ipynb', 'question61_80.ipynb', 'export_csv', 'question1_20.ipynb', 'iris.csv', 'NumPy.ipynb', 'weather.csv', 'sample.json', 'sample.png', 'lambda.ipynb', 'question41_60.ipynb', 'question21_40.ipynb', 'sample.txt']
['Untitled.ipynb', 'sample.py']
['sample-checkpoint.py', 'Untitled-checkpoint.ipynb']
['question41_60-checkpoint.ipynb', 'question81_100-checkpoint.ipynb', 'question61_80-checkpoint.ipynb', 'sample-checkpoint.png', 'people-checkpoint.csv', 'test_docPython-checkpoint.ipynb', 'sample-checkpoint.txt', 'question21_40-checkpoint.ipynb', 'export_csv-checkpoint', 'lambda-checkpoint.ipynb', 'question1_20-checkpoint.ipynb']
[]


In [11]:
for curDir, dirs, files in os.walk('.'):
    print(dirs)

['MatchCase', '.ipynb_checkpoints', 'sachiyo']
['.ipynb_checkpoints']
[]
[]
[]


In [40]:
for curDir, dirs, files in os.walk('.'):
    for file in files:
        print(f'{curDir}/file')

./file
./file
./file
./file
./file
./MatchCase/file
./MatchCase/file
./MatchCase/.ipynb_checkpoints/file
./MatchCase/.ipynb_checkpoints/file
./.ipynb_checkpoints/file
./.ipynb_checkpoints/file
./.ipynb_checkpoints/file
./.ipynb_checkpoints/file


In [26]:
os.listdir('.')

['MatchCase',
 'people.csv',
 'question81_100.ipynb',
 'test_docPython.ipynb',
 'Matplotlib.ipynb',
 'question61_80.ipynb',
 'question1_20.ipynb',
 'iris.csv',
 'weather.csv',
 'sample.json',
 '.ipynb_checkpoints',
 'question41_60.ipynb',
 'question21_40.ipynb',
 'sample.txt',
 'sachiyo']

In [27]:
lists = os.listdir('.')
lists.sort()
lists

['.ipynb_checkpoints',
 'MatchCase',
 'Matplotlib.ipynb',
 'iris.csv',
 'people.csv',
 'question1_20.ipynb',
 'question21_40.ipynb',
 'question41_60.ipynb',
 'question61_80.ipynb',
 'question81_100.ipynb',
 'sachiyo',
 'sample.json',
 'sample.txt',
 'test_docPython.ipynb',
 'weather.csv']

In [4]:
import os

In [41]:
os.path.abspath('./MatchCase/file')

'/Users/Sachiyo/Desktop/ImanyuDemo/MatchCase/file'

In [42]:
os.path.basename('./MatchCase/file')

'file'

In [43]:
os.path.exists('ma')

False

In [44]:
os.path.exists('MatchCase')

True

In [45]:
os.path.isdir('MatchCase')

True

In [15]:
os.path.isfile('sample.json')

True

In [56]:
os.mkdir('imanyu')

FileExistsError: [Errno 17] File exists: 'imanyu'

In [58]:
os.remove('sample.txt')

In [61]:
os.rename('imanyu', 'sachiyo')

FileNotFoundError: [Errno 2] No such file or directory: 'imanyu' -> 'sachiyo'

In [63]:
os.environ['PATH']

'/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'

In [5]:
os.system('ls -a')

.
..
.ipynb_checkpoints
MatchCase
Matplotlib.ipynb
NumPy.ipynb
export_csv
iris.csv
lambda.ipynb
people.csv
question1_20.ipynb
question21_40.ipynb
question41_60.ipynb
question61_80.ipynb
question81_100.ipynb
sachiyo
sample.json
sample.png
sample.txt
test_docPython.ipynb
weather.csv


0

In [29]:
print(os.popen('ls -a').read())

.
..
.ipynb_checkpoints
MatchCase
Matplotlib.ipynb
iris.csv
people.csv
question1_20.ipynb
question21_40.ipynb
question41_60.ipynb
question61_80.ipynb
question81_100.ipynb
sachiyo
sample.json
sample.txt
test_docPython.ipynb
weather.csv



In [67]:
!ls -a

.                   MatchCase           question41_60.ipynb
..                  question1_20.ipynb  sachiyo
.ipynb_checkpoints  question21_40.ipynb sample.json


In [31]:
import numpy as np

In [70]:
a = np.array([1, 2, 3, 4])

In [71]:
a

array([1, 2, 3, 4])

In [72]:
a.shape

(4,)

In [32]:
b = np.array([[1, 2],
        [3, 4]])

In [78]:
b

array([[1, 2],
       [3, 4]])

In [79]:
b.shape

(2, 2)

In [81]:
c = np.zeros(8)
c

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
c.shape

(8,)

In [83]:
d = np.zeros((4, 3))
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [84]:
d.shape

(4, 3)

In [85]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])